import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  autoSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  "docSidebar": [
        {
      type: 'category',
      label: 'Getting Started with Docker',
      link: { type: 'doc', id: 'Docker/Introduction' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Docker/Docs', // Generate sidebar slice from docs/Docker/Docs
        },
      ],      
   },
   {
    type: 'category',
    label: 'Nextcloud',
    link: { type: 'doc', id: 'Nextcloud/Introduction' },
    items: [
     {
          type: 'autogenerated',
          dirName: 'Nextcloud/Docs', // Generate sidebar slice from docs/Nextcloud/Docs
     },
    ],
  }, 
  {
    type: 'category',
    label: 'NextcloudPI',
    link: { type: 'doc', id: 'NextcloudPI/Introduction' },
    items: [
      {
          type: 'autogenerated',
          dirName: 'NextcloudPI/Docs', // Generate sidebar slice from docs/NextcloudPI/Docs
      },
    ],
  },
  { 
     type: 'category',
     label: 'MariaDb',
     items: [
       {
          type: 'autogenerated',
          dirName: 'MariaDB/Docs', // Generate sidebar slice from docs/MariaDB/Docs
      },
    ],
  },
  {  
     type: 'category',
     label: 'Docusaurus',
     link: { type: 'doc', id: 'Docusaurus/Introduction' },
     items: [
       {
          type: 'autogenerated',
          dirName: 'Docusaurus/Docs', // Generate sidebar slice from docs/Docusaurus/Docs
       },
     ],
   },
   {  
     type: 'category',
     label: 'Ubiquiti',
     link: { type: 'doc', id: 'Ubiquiti/Introduction' },
     items: [
      {
          type: 'autogenerated',
          dirName: 'Ubiquiti/Docs', // Generate sidebar slice from docs/Ubiquiti/Docs
      },
     ],
   },
   {  
     type: 'category',
     label: 'Reverse Proxy',
     link: { type: 'doc', id: 'Reverse Proxy/Introduction' },
     items: [
      {
          type: 'autogenerated',
          dirName: 'Reverse Proxy/Docs', // Generate sidebar slice from docs/Reverse Proxy/Docs
      },
   },
   {
     type: 'category',
     label: 'Jellyfin',
     link: { type: 'doc', id: 'Jellyfin/Introduction' },
     items: [
      {
          type: 'autogenerated',
          dirName: 'Jellyfin/Docs', // Generate sidebar slice from docs/Jellyfin/Docs
      },
     ],
   },
   {
     type: 'category',
     label: 'Discord',
     link: { type: 'doc', id: 'Discord/Introduction' },
     items: [
      {
          type: 'autogenerated',
          dirName: 'Discord/Docs', // Generate sidebar slice from docs/Discord/Docs
      },
     ],
   },
   {  
     type: 'category',
     label: 'Proxmox',
     link: { type: 'doc', id: 'Proxmox/Introduction' },
     items: [
      {
          type: 'category',
          label: 'LXC Containers',
          link: { type: 'doc', id: 'Proxmox/LXC Containers/Introduction' },
          items: [
           {
              type: 'category',
              label: 'Bind Mounts',
              link: { type: 'doc', id: 'Proxmox/LXC Containers/Bind Mounts/Introduction' },
              items: [
              ],
            },
           ],
         },
         {
           type: 'category',
           label: 'VM (Virtual Machines)',
           link: { type: 'doc', id: 'Proxmox/VM/Introduction' },
           items: [
           ],
         },
        ],
      },
  ],


  "exampleSidebar": [
        {
      type: 'category',
      label: 'Reverse Proxy',
      link: { type: 'doc', id: 'Examples/Reverse Proxies/Introduction' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'Examples/Reverse Proxies/Docs', // Generate sidebar slice from docs/Examples/Reverse Proxies/Docs
        },
      ],      
    },
   {
    type: 'category',
    label: 'Node-RED',
    link: { type: 'doc', id: 'Examples/Node-RED/Introduction' },
    items: [
     {
       type: 'autogenerated',
       dirName: 'Examples/Node-RED/Docs', // Generate sidebar slice from docs/Examples/Node-RED/Docs
     },   
    ],
  },
  {
    type: 'category',
    label: 'Arr Suite',
    link: { type: 'doc', id: 'Examples/Arr Suite/Introduction' },
    items: [
     {
       type: 'autogenerated',
       dirName: 'Examples/Arr Suite/Docs', // Generate sidebar slice from docs/Examples/Arr Suite/Docs
     },
    ],
   },
   {
    type: 'category',
    label: 'VPN',
    link: { type: 'doc', id: 'Examples/VPN/Introduction' },
    items: [
     {
       type: 'autogenerated',
       dirName: 'Examples/VPN/Docs', // Generate sidebar slice from docs/tutorials/advanced
     }
    ],
   },
 ],
  "MSwindowsSidebar": [
    {
      type: 'category',
      label: 'Windows',
      link: { type: 'doc', id: 'MS Windows/Windows/Introduction' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MS Windows/Windows/Docs', // Generate sidebar slice from docs/MS Windows/Windows/Docs
        },
      ],
    },
    {
      type: 'category',
      label: 'Microsoft Office',
      link: { type: 'doc', id: 'MS Windows/Microsoft Office/Introduction' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MS Windows/Microsoft Office/Docs', // Generate sidebar slice from docs/MS Windows/Microsoft Office/Docs
        },
      ],
    },
    {
      type: 'category',
      label: 'Local KMS',
      link: { type: 'doc', id: 'MS Windows/Local KMS/Introduction' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MS Windows/Local KMS/Docs', // Generate sidebar slice from docs/MS Windows/Local KMS/Docs
        },
      ],
    },
   ],
};

export default sidebars;
