import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  autoSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  
  "docSidebar": [
        {
      type: 'category',
      label: 'Getting Started with Docker',
      link: { type: 'doc', id: 'Docker/Introduction' },
      items: [
        {
          type: 'category',
          label: 'Installation',
          items: [
            'Docker/Installing Docker/Docker Engine',
            'Docker/Installing Docker/Docker-Compose',
          ],
        },
         'Docker/Docs/Helpful Commands',
         'Docker/Troubleshooting/Docker',
      ],      
   },
   {
    type: 'category',
    label: 'Nextcloud',
    link: { type: 'doc', id: 'Nextcloud/Introduction' },
    items: [
     {
        type: 'category',
        label: 'Installation',
        items: [
          'Nextcloud/Installation/Minimum',
          'Nextcloud/Installation/Collabora',
          'Nextcloud/Installation/Memories',
          'Nextcloud/Installation/Complete',
         ],
      },   
        'Nextcloud/Docs/Updating',
        'Nextcloud/Docs/Pre-built Images',
        'Nextcloud/Docs/Helpful Commands',
     {
       type: 'category',
       label: 'Troubleshooting',
       items: [
         'Nextcloud/Troubleshooting/Nextcloud',
         'Nextcloud/Troubleshooting/Nextcloud Memories',
         'Nextcloud/Troubleshooting/Collabora Code',
         'Nextcloud/Troubleshooting/OnlyOffice',
        ],
     },
     ],
  }, 
  {
    type: 'category',
    label: 'NextcloudPI',
    link: { type: 'doc', id: 'NextcloudPI/Introduction' },
    items: [
        'NextcloudPI/Installation/Install',
    ],
  },
  { 
     type: 'category',
     label: 'MariaDb',
     items: [
         'MariaDB/Updating',
    ],
  },
  {  
     type: 'category',
     label: 'Docusaurus',
     link: { type: 'doc', id: 'Docusaurus/Introduction' },
     items: [
         'Docusaurus/Docs/Installation',
         'Docusaurus/Docs/Algolia-Search',
         'Docusaurus/Docs/Docs Only Mode',
         'Docusaurus/Docs/Connecting to GitHub',
         'Docusaurus/Docs/Migration',
         {
          type: 'category',
          label: 'Troubleshooting',
          items: [
            'Docusaurus/Troubleshooting/Docusaurus',
            'Docusaurus/Troubleshooting/Algolia',
            'Docusaurus/Troubleshooting/GitHub',
          ],
         },
     ],
   },
   {  
     type: 'category',
     label: 'Ubiquiti',
     link: { type: 'doc', id: 'Ubiquiti/Introduction' },
     items: [
      {
        type: 'category',
        label: 'Access Points',
        link: { type: 'doc', id: 'Ubiquiti/Access Points/Introduction' },
        items: [
          'Ubiquiti/Access Points/Unifi Controller Server',
        ],
      },
     ],
   },
   {  
     type: 'category',
     label: 'Reverse Proxy',
     link: { type: 'doc', id: 'Reverse Proxy/Introduction' },
     items: [
      {
        type: 'category',
        label: 'Nginx',
        link: { type: 'doc', id: 'Reverse Proxy/Nginx/Introduction' },
        items: [
          'Reverse Proxy/Nginx/Installing Nginx',
        ],
      },
      {
        type: 'category',
        label: 'Certbot',
        link: { type: 'doc', id: 'Reverse Proxy/Certbot/Introduction' },
        items: [
          {
            type: 'category',
            label: 'Cloudflare',
            link: { type: 'doc', id: 'Reverse Proxy/Certbot/Cloudflare/Introduction' },
            items: [
              'Reverse Proxy/Certbot/Cloudflare/Cloudflare',
            ],
          },
        ],
      },
     ],
   },
      {
        type: 'category',
        label: 'Jellyfin',
        link: { type: 'doc', id: 'Jellyfin/Introduction' },
        items: [
          {
            type: 'category',
            label: 'Installation',
            link: { type: 'doc', id: 'Jellyfin/Installation/Introduction' },
            items: [
              'Jellyfin/Installation/Docker Install',
              'Jellyfin/Installation/Host Install',
            ],
          },
        ],
      },
      {
        type: 'category',
        label: 'Discord',
        link: { type: 'doc', id: 'Discord/Introduction' },
        items: [
          {
            type: 'category',
            label: 'Bots',
            link: { type: 'doc', id: 'Discord/Bots/Introduction' },
            items: [
              'Discord/Bots/AI Bot',
            ],
          },
        ],
      },
      {  
        type: 'category',
        label: 'Proxmox',
        link: { type: 'doc', id: 'Proxmox/Introduction' },
        items: [
         {
           type: 'category',
           label: 'LXC Containers',
           link: { type: 'doc', id: 'Proxmox/LXC Containers/Introduction' },
           items: [
            {
              type: 'category',
              label: 'Bind Mounts',
              link: { type: 'doc', id: 'Proxmox/LXC Containers/Bind Mounts/Introduction' },
              items: [
              ],
            },
           ],
         },
         {
           type: 'category',
           label: 'VM (Virtual Machines)',
           link: { type: 'doc', id: 'Proxmox/VM/Introduction' },
           items: [
           ],
         },
        ],
      },
  ],


  "exampleSidebar": [
        {
      type: 'category',
      label: 'Reverse Proxy',
      link: { type: 'doc', id: 'Examples/Reverse Proxies/Introduction' },
      items: [
        {
          type: 'category',
          label: 'Nginx',
          items: [
            'Examples/Reverse Proxies/Nginx/Nginx',
          ],
        },
      ],      
    },
   {
    type: 'category',
    label: 'Node-RED',
    link: { type: 'doc', id: 'Examples/Node-RED/Introduction' },
    items: [
     {
        type: 'category',
        label: 'Flows',
        items: [
          'Examples/Node-RED/Flows/Flows',
         ],
      },   
    ],
  },
  {
    type: 'category',
    label: 'Arr Suite',
    link: { type: 'doc', id: 'Examples/Arr Suite/Introduction' },
    items: [
     {
        type: 'category',
        label: 'Full Stack',
        items: [
          'Examples/Arr Suite/Full Stack/docker-compose',
         ],
      },  
      {
        type: 'category',
        label: 'Jellyseerr',
        items: [
          'Examples/Arr Suite/Jellyseerr/docker-compose',
         ],
      },
      {
        type: 'category',
        label: 'Radarr',
        items: [
          'Examples/Arr Suite/Radarr/docker-compose',
         ],
      },
      {
        type: 'category',
        label: 'Sonarr',
        items: [
          'Examples/Arr Suite/Sonarr/docker-compose',
         ],
      }, 
      {
        type: 'category',
        label: 'Lidarr',
        items: [
          'Examples/Arr Suite/Lidarr/docker-compose',
         ],
      }, 
      {
        type: 'category',
        label: 'Readarr',
        items: [
          'Examples/Arr Suite/Readarr/docker-compose',
         ],
      }, 
      {
        type: 'category',
        label: 'Prowlarr',
        items: [
          'Examples/Arr Suite/Prowlarr/docker-compose',
         ],
      },
     ],
   },
   {
    type: 'category',
    label: 'VPN',
    link: { type: 'doc', id: 'Examples/VPN/Introduction' },
    items: [
     {
        type: 'category',
        label: 'Firewall',
        items: [
          'Examples/VPN/Firewall/Linux Firewall',
         ],
      },
      {
        type: 'category',
        label: 'Testing',
        items: [
          'Examples/VPN/Testing/dnsleaktest',
         ],
      },
     ],
   },
 ],
  "MSwindowsSidebar": [
    {
      type: 'category',
      label: 'Windows',
      link: { type: 'doc', id: 'MS Windows/Windows/Introduction' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MS Windows/Windows', // Generate sidebar slice from docs/MS Windows/Windows
        },
      ],
    },
    {
      type: 'category',
      label: 'Microsoft Office',
      link: { type: 'doc', id: 'MS Windows/Microsoft Office/Introduction' },
      items: [
        {
          type: 'autogenerated',
          dirName: 'MS Windows/Microsoft Office', // Generate sidebar slice from docs/MS Windows/Microsoft Office
        },
      ],
    },
    {
      type: 'category',
      label: 'Local KMS',
      items: [
        'MS Windows/Local KMS/Introduction',
        {
          type: 'autogenerated',
          dirName: 'MS Windows/Local KMS', // Generate sidebar slice from docs/MS Windows/Local KMS
        },
      ],
    },
   ],
};

export default sidebars;
